apiVersion: v1
kind: Service
metadata:
  name: commands-web-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: commands-web-app
  ports:
  - name: commands-web-app
    protocol: TCP
    port: 80
    targetPort: 80