apiVersion: v1
kind: Service
metadata:
  name: commands-mssql-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: commands-mssql-app
  ports:
  - name: commands-mssql-app
    protocol: TCP
    port: 1433
    targetPort: 1433