apiVersion: v1
kind: Service
metadata:
  name: commands-web-node-port-service
spec:
  type: NodePort
  selector:
    app: commands-web-app
  ports:
    - name: commands-http-port
      protocol: TCP
      port: 80
      targetPort: 80