apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commands-service
  template:
    metadata:
      labels:
        app: commands-service
    spec:
      containers:
        - name: commands-service
          image: esaf/it-service-tools.commands-service:latest