apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-mssql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commands-mssql-app
  template:
    metadata:
      labels:
        app: commands-mssql-app
    spec:
      containers:
        - name: commands-mssql-app
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: commands-mssql-secret
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data/commands
            name: commands-mssql-volume
      volumes:
      - name: commands-mssql-volume
        persistentVolumeClaim:
          claimName: commands-pvc