apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commands-web-app
  template:
    metadata:
      labels:
        app: commands-web-app
    spec:
      containers:
        - name: commands-web-app
          image: esaf/it-service-tools.commands-service:latest