apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
        - name: platform-service
          image: esaf/it-service-tools.platform-service:latest