apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platforms-web-app
  template:
    metadata:
      labels:
        app: platforms-web-app
    spec:
      containers:
        - name: platforms-web-app
          image: esaf/it-service-tools.platform-service:latest