apiVersion: v1
kind: Service
metadata:
  name: platforms-mssql-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: platforms-mssql-app
  ports:
  - name: platforms-http-port
    protocol: TCP
    port: 1433
    targetPort: 1433