apiVersion: v1
kind: Service
metadata:
  name: platforms-web-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: platforms-web-app
  ports:
  - name: platforms-web-app
    protocol: TCP
    port: 80
    targetPort: 80