apiVersion: v1
kind: Service
metadata:
  name: platforms-web-node-port-service
spec:
  type: NodePort
  selector:
    app: platforms-web-app
  ports:
    - name: platforms-web-app
      protocol: TCP
      port: 80
      targetPort: 80